#!/bin/ksh
# /etc/rc.d/openhapd
#
# OpenHAP daemon rc.d script for OpenBSD

daemon="/usr/local/bin/openhapd"
daemon_flags="-c /etc/openhapd.conf"
daemon_user="_openhap"

. /etc/rc.d/rc.subr

rc_configtest() {
    ${daemon} -n ${daemon_flags}
}

rc_reload() {
    pkill -HUP -U ${daemon_user} -xf "${pexp}"
}

pexp="perl ${daemon}.*"

rc_cmd $1
