.\" $OpenBSD$
.\"
.\" Copyright (c) 2025 Dick Olsson <hi@senzilla.io>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: December 26 2025 $
.Dt HAPCTL 8
.Os
.Sh NAME
.Nm hapctl
.Nd control utility for openhapd
.Sh SYNOPSIS
.Nm hapctl
.Op Fl c Ar file
.Ar command
.Sh DESCRIPTION
.Nm
is a command-line utility for the
.Xr openhapd 8
daemon.
It does a check of the configuration file.
It shows if the daemon runs and if it is paired.
It shows a list of the configured devices.
.Pp
The options are:
.Bl -tag -width Ds
.It Fl c Ar file
Read the configuration from
.Ar file .
The default is
.Pa /etc/openhapd.conf .
.El
.Pp
These commands are available:
.Bl -tag -width "devicesXX"
.It Cm check
Do a check of the configuration file syntax.
The command parses
.Xr openhapd.conf 5
and shows syntax errors and values that are not valid.
If the configuration is correct, the command exits with status 0.
If it is not, the exit status is not 0.
The command also shows the number of configured devices.
.It Cm status
Show the status of the
.Xr openhapd 8
daemon and the pairing data.
The command shows if the daemon runs, and it shows the process
ID and the pairing state (paired, unpaired, or unknown).
For a paired accessory, the command shows the number of paired
HomeKit controllers.
.It Cm devices
Show all devices that
.Xr openhapd.conf 5
configures.
For each device, the command shows:
.Bl -bullet -compact
.It
The device name, as HomeKit shows it
.It
The device type and subtype
.It
The MQTT topic prefix
.It
The internal device identifier
.El
.It Cm help
Show the usage message.
.El
.Sh FILES
.Bl -tag -width "/var/db/openhapd/pairingsXX" -compact
.It Pa /etc/openhapd.conf
The default configuration file.
.It Pa /var/run/openhapd.pid
The process ID of the daemon when it runs.
.It Pa /var/db/openhapd/pairings
The pairing database for status checks.
.El
.Sh EXIT STATUS
.Ex -std
The commands exit with status 0 on success.
.Pp
The
.Cm check
command exits with a status that is not 0 if it finds configuration
errors.
.Pp
The
.Cm status
and
.Cm devices
commands always exit with status 0.
The daemon state has no effect on their exit status.
.Sh EXAMPLES
Do a check of the configuration file:
.Bd -literal -offset indent
$ hapctl check
Configuration file /etc/openhapd.conf is valid
  Configured devices: 3
.Ed
.Pp
Show the daemon status:
.Bd -literal -offset indent
$ hapctl status
openhapd is running (PID 12345)
Pairing status: paired (2 controllers)
.Ed
.Pp
Show the configured devices:
.Bd -literal -offset indent
$ hapctl devices
Configured devices: 2

  Bedroom Thermostat
    Type:  tasmota/thermostat
    Topic: tasmota_AABBCC
    ID:    bedroom

  Living Room Thermostat
    Type:  tasmota/thermostat
    Topic: tasmota_DDEEFF
    ID:    living_room
.Ed
.Pp
Use a different configuration file:
.Bd -literal -offset indent
$ hapctl -c /etc/openhapd.test.conf check
.Ed
.Sh DIAGNOSTICS
.Nm
writes configuration errors to
.Em stderr ,
with a message that describes each error.
.Pp
If
.Xr openhapd 8
does not run,
.Cm status
shows:
.Bd -literal -offset indent
openhapd is not running
.Ed
.Pp
If
.Nm
cannot read the pairing database,
.Cm status
shows:
.Bd -literal -offset indent
Pairing status: unknown (cannot read storage)
.Ed
.Sh SEE ALSO
.Xr openhapd.conf 5 ,
.Xr openhapd 8 ,
.Xr rc 8
.Sh HISTORY
The
.Nm
utility was first available with
.Xr openhapd 8
in 2025.
.Sh AUTHORS
.An Dick Olsson Aq Mt hi@senzilla.io
.Sh CAVEATS
.Nm
reads the pairing database directly to get the pairing status.
Thus, it must have read access to
.Pa /var/db/openhapd/ .
When a user who is not root runs
.Nm ,
the command can show the pairing status as
.Dq unknown .
