.\" $OpenBSD$
.\"
.\" Copyright (c) 2025 Dick Olsson <hi@senzilla.io>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: December 26 2025 $
.Dt OPENHAPD.CONF 5
.Os
.Sh NAME
.Nm openhapd.conf
.Nd OpenHAP daemon configuration file
.Sh DESCRIPTION
.Nm
is the configuration file for the
.Xr openhapd 8
daemon.
The file uses a simple key-value format with device blocks that
define HomeKit accessories.
.Pp
A line that starts with
.Sq #
is a comment, and the daemon ignores it.
.Sh GLOBAL OPTIONS
These global options are available:
.Bl -tag -width Ds
.It Ic hap_name Ar string
The name of the HomeKit bridge, as the iOS Home app shows it.
Default:
.Dq OpenHAP Bridge .
.It Ic hap_port Ar number
The TCP port for the HAP server.
Default: 51827.
.It Ic hap_pin Ar XXXX-XXXX
The 8-digit setup code for pairing.
The format is XXXX-XXXX.
Each X is a digit 0-9.
The dashes only make the code easy to read.
The daemon removes them when it parses the value.
The HAP specification does not permit these values (after removal of
the dashes):
00000000, 11111111, 22222222, 33333333, 44444444,
55555555, 66666666, 77777777, 88888888, 99999999,
12345678, 87654321.
Default: 1995-1018.
.It Ic hap_model Ar string
The model name that the daemon sends to HomeKit.
Default:
.Dq OpenHAP .
.It Ic hap_manufacturer Ar string
The manufacturer name that the daemon sends to HomeKit.
Default:
.Dq OpenBSD .
.It Ic db_path Ar path
The directory that holds the pairing database and the cryptographic
keys.
Default:
.Pa /var/db/openhapd .
.It Ic log_level Ar level
The log verbosity level.
The valid values are:
.Cm debug , info , notice , warning , err , crit , alert , emerg .
Default:
.Cm info .
.It Ic log_facility Ar facility
The syslog facility for the log messages.
The valid values are:
.Cm daemon , local0 Ns \(en Ns Cm local7 , user .
Default:
.Cm daemon .
.It Ic mqtt_host Ar hostname
The hostname or the IP address of the MQTT broker.
Default: 127.0.0.1.
.It Ic mqtt_port Ar number
The TCP port of the MQTT broker.
Default: 1883.
.It Ic mqtt_user Ar username
The username for MQTT authentication.
This option is optional.
.It Ic mqtt_pass Ar password
The password for MQTT authentication.
This option is optional.
.El
.Sh DEVICE BLOCKS
Define each device with this syntax:
.Bd -literal -offset indent
device <type> <subtype> <id> {
    name = "<display name>"
    topic = "<mqtt topic>"
    [more options...]
}
.Ed
.Pp
The parameters are:
.Bl -tag -width "subtypeXX"
.It Ar type
The device driver type.
At this time, only
.Cm tasmota
is available.
.It Ar subtype
The device subtype.
For
.Cm tasmota ,
the valid values are:
.Cm thermostat , heater , sensor .
.It Ar id
The unique identifier of the device in the configuration.
The daemon uses it for internal reference.
.It Ic name
The display name that the iOS Home app shows.
This option is necessary.
.It Ic topic
The MQTT topic prefix for the device.
For Tasmota devices, this is the topic from the MQTT settings of the
device.
The default of that setting is
.Dq tasmota_%06X .
The %06X part is the last 6 hex digits of the MAC address.
This option is necessary.
.El
.Pp
The other options are different for each device subtype:
.Ss Thermostat Options
Tasmota thermostat devices have these options:
.Bl -tag -width "target_temp_topicXX"
.It Ic current_temp_topic Ar topic
The MQTT topic for the current temperature values.
Default:
.Ar topic Ns /SENSOR .
.It Ic target_temp_topic Ar topic
The MQTT topic for the target temperature.
Default:
.Ar topic Ns /TARGET .
.It Ic state_topic Ar topic
The MQTT topic for the heater state (on or off).
Default:
.Ar topic Ns /STATE .
.It Ic min_temp Ar celsius
The minimum temperature in Celsius.
Default: 10.0.
.It Ic max_temp Ar celsius
The maximum temperature in Celsius.
Default: 30.0.
.It Ic temp_step Ar celsius
The step size for temperature adjustment.
Default: 0.5.
.El
.Sh FILES
.Bl -tag -width "/var/db/openhapd/XX" -compact
.It Pa /etc/openhapd.conf
The default location of the configuration file.
.It Pa /etc/examples/openhapd.conf
The example configuration file that
.Cm make install
installs.
.El
.Sh EXAMPLES
A minimal configuration with one thermostat:
.Bd -literal -offset indent
hap_name = "Home Bridge"
hap_pin = 9876-5432

mqtt_host = 192.168.1.10

device tasmota thermostat bedroom {
    name = "Bedroom Thermostat"
    topic = tasmota_AABBCC
}
.Ed
.Pp
Three devices with custom MQTT settings:
.Bd -literal -offset indent
hap_name = "OpenHAP"
hap_port = 51827
hap_pin = 1112-2333

mqtt_host = mqtt.local
mqtt_port = 1883
mqtt_user = homekit
mqtt_pass = secretpassword

log_level = debug
log_facility = local0

device tasmota thermostat bedroom {
    name = "Bedroom"
    topic = tasmota_AABBCC
    min_temp = 15.0
    max_temp = 25.0
}

device tasmota thermostat living_room {
    name = "Living Room"
    topic = tasmota_DDEEFF
}

device tasmota thermostat kitchen {
    name = "Kitchen"
    topic = tasmota_112233
}
.Ed
.Sh SEE ALSO
.Xr syslog.conf 5 ,
.Xr hapctl 8 ,
.Xr mdnsd 8 ,
.Xr mosquitto 8 ,
.Xr openhapd 8
.Sh STANDARDS
The MQTT topic structure obeys the Tasmota firmware conventions.
See
.Lk https://tasmota.github.io/docs/MQTT/
for more data on the Tasmota MQTT topics.
.Sh HISTORY
The
.Nm
file format was first available with
.Xr openhapd 8
in 2025.
.Sh AUTHORS
.An Dick Olsson Aq Mt hi@senzilla.io
.Sh CAVEATS
The configuration file holds the
.Ic hap_pin
in plain text.
Make sure that the file permissions are correct:
mode 0600, with root as the owner.
.Pp
If you change the
.Ic hap_name
or the
.Ic hap_pin
after pairing, it can be necessary to pair all controllers again.
.Pp
The file holds
.Ic mqtt_pass
in plain text, and the daemon sends it to the broker without
encryption.
.Xr openhapd 8
does not use MQTT over TLS.
Keep the broker on the local machine or on a trusted network.
