name: "Setup Perl with dependencies"
description: "Install system dependencies and set up Perl for OpenHAP"

runs:
  using: "composite"
  steps:
    - name: Install system dependencies and Perl toolchain
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cpanminus \
          liblocal-lib-perl \
          libssh2-1-dev

    - name: Configure local::lib environment
      shell: bash
      run: |
        mkdir -p "${{ github.workspace }}/local"
        echo "PERL5LIB=${{ github.workspace }}/local/lib/perl5" >> $GITHUB_ENV
        echo "PERL_LOCAL_LIB_ROOT=${{ github.workspace }}/local" >> $GITHUB_ENV
        echo "PERL_MB_OPT=--install_base ${{ github.workspace }}/local" >> $GITHUB_ENV
        echo "PERL_MM_OPT=INSTALL_BASE=${{ github.workspace }}/local" >> $GITHUB_ENV
        echo "${{ github.workspace }}/local/bin" >> $GITHUB_PATH
