=head1 NAME

OpenHAP::Config - Configuration file parser

=head1 SYNOPSIS

    use OpenHAP::Config;

    my $config = OpenHAP::Config->new(file => '/etc/openhapd.conf');
    $config->load();

    my $name = $config->get('hap_name', 'Home Bridge');
    my @devices = $config->get_devices();

=head1 DESCRIPTION

This module parses OpenHAP configuration files.

=cut
