=head1 NAME

OpenHAP::HTTP - HTTP/1.1 parser for the HAP protocol

=head1 SYNOPSIS

    use OpenHAP::HTTP;

    # Parse HTTP request
    my $request = OpenHAP::HTTP::parse($data);
    print $request->{method}, " ", $request->{path}, "\n";

    # Build HTTP response
    my $response = OpenHAP::HTTP::build_response(
        status => 200,
        headers => { 'Content-Type' => 'application/hap+json' },
        body => $json_data,
    );

=head1 DESCRIPTION

This module supplies a simple HTTP/1.1 parser and a response builder
for the HomeKit Accessory Protocol.

=head1 FUNCTIONS

=head2 parse($data)

This function parses the HTTP request data. It returns a hashref with
these keys:

=over 4

=item * C<method> - The HTTP method (GET, POST, PUT)

=item * C<path> - The request path

=item * C<version> - The HTTP version

=item * C<headers> - A hash of the headers (lowercase keys)

=item * C<body> - The request body

=back

=head2 build_response(%args)

This function builds an HTTP response. These are the arguments:

=over 4

=item * C<status> - The HTTP status code (default: 200)

=item * C<status_text> - The status text. If it is not given, the
function generates it.

=item * C<headers> - A hashref of the headers

=item * C<body> - The response body

=back

=head1 SEE ALSO

F<spec/HAP-HTTP.md>

=cut
