=head1 NAME

OpenHAP::Service - HAP service definitions

=head1 SYNOPSIS

    use OpenHAP::Service;

    my $service = OpenHAP::Service->new(
        type => 'Thermostat',
        iid => 10,
    );

    $service->add_characteristic($characteristic);

=head1 DESCRIPTION

This module represents HAP services that contain related characteristics.

=cut
