=head1 NAME

OpenHAP::SRP - SRP-6a implementation for HAP pairing

=head1 SYNOPSIS

    use OpenHAP::SRP;

    # Server side
    my $srp = OpenHAP::SRP->new(password => $pin);
    my $salt = $srp->generate_salt();
    my $v = $srp->compute_verifier($salt, $password);
    my $B = $srp->generate_server_public();

    # After receiving client's A
    my $K = $srp->compute_session_key($A);
    my $valid = $srp->verify_client_proof($M1);
    my $M2 = $srp->generate_server_proof();

=head1 DESCRIPTION

This module implements SRP-6a protocol for HomeKit pairing.

=cut
