=head1 NAME

OpenHAP::Tasmota::Heater - Tasmota heater/switch HAP accessory

=head1 SYNOPSIS

    use OpenHAP::Tasmota::Heater;

    my $heater = OpenHAP::Tasmota::Heater->new(
        aid => 2,
        name => 'Living Room Heater',
        mqtt_topic => 'tasmota_AABBCC',
        mqtt_client => $mqtt,
    );

=head1 DESCRIPTION

This module implements a HAP switch accessory for Tasmota devices
with relay control (heaters, switches, outlets).

=cut
